### ISSUE TITLE
<>No module named 'Queue'

### ISSUE THREAD

**Issue by irs4675** [infosec-au/altdns#13]
I got this exceprion when use python altdns.py

Traceback (most recent call last):
  File "altdns.py", line 11, in <module>
    import Queue as Queue
ImportError: No module named 'Queue'

so .. I think 
`from Queue import Queue as Queue`
should be
`from multiprocessing import Queue`

**Comment by gehaxelt** [comment]
Hi @irs4675 
afaik this script is written for python2, not python3. At least switching to python2 solved the problem for me. 

See: https://stackoverflow.com/questions/29687837/queue-importerror-in-python-3

**Comment by krishanukc** [comment]
Try the command as : python3 altdns -i .........
