### ISSUE TITLE
Feature: Make it available in python pip

### ISSUE THREAD

**Issue by vdun** [infosec-au/altdns#18]

**Comment by fabaff** [comment]
The only option to make that happen seems to be forking as there is not much development going on.

I could help because at the end I'm interested in including `altdns` into the Fedora Security Lab and for this are certain requirement needed like a `setup.py` file.

**Comment by infosec-au** [comment]
Hi Fabian,

I’m happy to maintain this. Please give me the weekend to resolve or
comment on any issues.

Cheers

**Comment by infosec-au** [comment]
Issue resolved.

`pip install py-altdns`

Cheers
