### ISSUE TITLE
Wildcard DNS detection?

### ISSUE THREAD

**Issue by gehaxelt** [infosec-au/altdns#2]
Hi, 

when using altdns with the `-r` switch and scanning a wildcard domain you'll get a lot of invalid results. 

It would be nice to have some kind of wildcard dns detection to skip such domains. 

Regards,
gehaxelt

**Comment by infosec-au** [comment]
Hey @gehaxelt,

At the moment, there are no plans to support wildcard DNS detection. I would recommend using the output file (that contains every possible permutation) with your favorite DNS bruteforcing tool of choice (subbrute for example) which supports wildcard detection.

Thanks for taking a look at this project :)
