### ISSUE TITLE
No module named 'queue' 

### ISSUE THREAD

**Issue by zongdeiqianxing** [infosec-au/altdns#29]
No module named 'queue'  or No module named 'Queue'

**Comment by nature1995** [comment]
You need have 2 options:
1. You can change the /lib/python3.6/site-packages/altdns/__main__.py 
```
# From
from Queue import Queue as Queue
# To
from queue import Queue as Queue
```
2. You can use the newest code in github
```
git clone https://github.com/infosec-au/altdns.git
python setup.py build
python setup.py install
```

**Comment by Mirhatyasar** [comment]
i'm getting this issue and both of the solutions didn't work for me

**Comment by Mirhatyasar** [comment]
i fixed this issue by doing: 
1. cd altdns
2. open __main.py__ in linux i did nano __main.py__
3. comment out from queue import Queue as Queue by adding # in the beginning
4. add from multiprocessing import Queue

**Comment by niksthehacker** [comment]
edit main.py and replace

```
from Queue import Queue as Queue
```
to this
```
from multiprocessing import Queue as Queue
```
