### ISSUE TITLE
This tool still has the same python compatiblity issues and fails to start and the devolper doesn`t give a f

### ISSUE THREAD

**Issue by Sakuragi-Hanamichii** [infosec-au/altdns#53]
I have been trying to get it to work. and went through the issues and users luck but still no luck.

This tool is not maintained so don`t waste your time and fuck python.

**Comment by infosec-au** [comment]
Hey @Sakuragi-Hanamichii this tool is not maintained as there are several better implementations of this now available: 

https://blog.projectdiscovery.io/introducing-alterx-simplifying-active-subdomain-enumeration-with-patterns/
https://github.com/bp0lr/dmut

Please give these other tools a go :)
